I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/combat4.rpy", line 34, in script
    $ random4 == d4
  File "game/combat4.rpy", line 34, in <module>
    $ random4 == d4
NameError: name 'random4' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/combat4.rpy", line 34, in script
    $ random4 == d4
  File "C:\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/combat4.rpy", line 34, in <module>
    $ random4 == d4
NameError: name 'random4' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.1.24030407
The Chosen One 1.3
Wed Aug 14 10:44:10 2024
